### ISSUE TITLE
How to cache retrieved access token

### ISSUE THREAD

**Issue by ametad** [frankkessler/guzzle-oauth2-middleware#17]
In the docs you state:

> Acquires access tokens via one of the supported grant types (code, client credentials, user credentials, refresh token). **Or you can set an access token yourself**.

> // Use $client->getAccessToken(); and $client->getRefreshToken() to get tokens
> // that can be persisted for subsequent requests.

What would be the correct implementation of how to cache a acquired access token (say via client credentials grant) and then use that, until the access token is not valid anymore (it could be expired e.g.)?

**Comment by ametad** [comment]
The reason I ask is I cannot find the right 'hook' or approach how to know the used access token is somehow rejected by the server. When a token is rejected it should be removed from cache, a new token acquired and stored in cache for further use.

**Comment by mirfilip** [comment]
I had the same question when I first found this library. The answer I came up with is to add your own middleware that reads the token from persistence layer (e.g. DB) and sets it with `Oauth2Client::setAccessToken`. If you use refresh tokens, store them and do the same. When fetched token is stale, this library will do magic with asking for new token or using refresh token. Anyway, after the new token is used for the resource call, you can get it by `Oauth2Client::getAccessToken` and persist it once again.

For your second question: you can specify your own `token_handler` and hook with your response middleware. There, you can inspect if the response was "invalid token" and remove that token from persistence. Or you can let the stale token exist in persistence and overwrite it after acquiring a new one.

**Comment by ametad** [comment]
Thanks @mirfilip !

The part about setting the access token yourself I understand. For now I set the token right after creating the Oauth2Client. 

My question about how to know when the access token is not accepted by the server; you have pointed me in the right direction I think...

The thing is, after storing the access token how would you know the token must be updated in storage? Because this plugin fetches a new token automatically and - as far as I can tell - there is no implementation to check there is a new token. Or do I miss something?

What I perhaps could do is 

- create a new stack handler
- this handler checks with the same criteria as Oauth2Client handler does, and
- if necessary remove or update the old access token

Going to work you think?

**Comment by ametad** [comment]
For now I just always cache the token after the call has been made. And before making the call I set the token from cache.

This means if no token was needed, the call to oauth/token is made anyway. This is the only efficiency drawback I see... But it's not that big a problem.

**Comment by mirfilip** [comment]
Late to the party, @ametad, but:
Assuming you have a long running PHP process (not request based), the flow is:
1. Create a client
2. Access token is not set - ask for one and store it in `Oauth2Client:: setAccessToken`.
3. As long as the client object lives, the access token is going to be used. 
4. When PHP process lives longer than token expiry, eventually you'll run into "invalid token error" when performing "main request" with token stored in `Oauth2Client` private member. That's also the place to hook into (main handler of Oauth2Client) to get the idea whether request failed with that exact error. Depending on your approach, you can invalidate/remove previosly persisted token here, or do nothing.
5. Ask for a fresh token, store it in `Oauth2Client:: setAccessToken` and redo a main request.

So, that's the basic flow of this lib and more verbose version of what I wrote before. It doesn't matter whether it's a long running PHP process that has a client instance alive for long time (and token stored in a private member) or a standard PHP app (request-based) where you need to persist a token to reuse it between requests.

What you do now is correct - get the token from cache before making a request. When it's stale, you'll have to go back to persistence layer and update it. I'm not sure I understand 
> This means if no token was needed, the call to oauth/token is made anyway.
the whole point of our discussion is to avoid it. You store it in some persistence layer and fetch that before creating a client instance - this way you can set the token before making a call.
